import React, { useState } from 'react';
import { X, RefreshCw, Upload, ShieldCheck, Copy, Check } from 'lucide-react';
import { AppSettings, ReloadTransaction } from '../types';
import { apiCreateReload } from '../utils/api';

interface Props { settings: AppSettings; isOpen: boolean; onClose: ()=>void; }
export const ReloadCardModal: React.FC<Props> = ({settings,isOpen,onClose}) => {
  const [identifier,setIdentifier]=useState(''); const [securityKey,setSecurityKey]=useState(''); const [amount,setAmount]=useState(25);
  const [method,setMethod]=useState<'esewa'|'crypto'>('esewa'); const [txid,setTxid]=useState(''); const [txurl,setTxurl]=useState('');
  const [shot,setShot]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState<ReloadTransaction|null>(null); const [error,setError]=useState(''); const [copied,setCopied]=useState(false);
  if(!isOpen)return null;
  const cryptoMethod=settings.payment_methods?.find(m=>m.type==='crypto'&&m.enabled); const esewaMethod=settings.payment_methods?.find(m=>m.type==='esewa'&&m.enabled);
  const fileToData=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{if(!identifier||!securityKey)throw new Error('Enter your Order ID, email, or full card number plus your CVV/cardholder name.'); if(method==='crypto'&&!txid.trim())throw new Error('Crypto Transaction ID is required.'); if(method==='esewa'&&!shot)throw new Error('eSewa payment screenshot is required.'); const r=await apiCreateReload({identifier,security_key:securityKey,amount_usd:amount,payment_method:method,transaction_id:txid.trim()||undefined,transaction_url:txurl.trim()||undefined,payment_screenshot_url:shot||undefined});setResult(r);}catch(e:any){setError(e.message||'Reload request failed.')}finally{setLoading(false)}};
  const copy=async()=>{if(result){await navigator.clipboard.writeText(result.reload_id);setCopied(true);setTimeout(()=>setCopied(false),1200)}};
  return <div className="fixed inset-0 z-[70] bg-black/80 backdrop-blur-sm p-0 sm:p-4 flex items-end sm:items-center justify-center"><div className="w-full sm:max-w-xl max-h-[96vh] overflow-y-auto rounded-t-3xl sm:rounded-3xl border border-white/10 bg-[#0d0d0f] shadow-2xl pb-[env(safe-area-inset-bottom)]">
    <div className="sticky top-0 z-10 flex items-center justify-between p-4 sm:p-5 border-b border-white/10 bg-[#0d0d0f]/95 backdrop-blur"><div><h2 className="font-black text-white flex items-center gap-2"><RefreshCw className="w-5 h-5 text-[#D4AF37]"/> Reload My Card</h2><p className="text-[11px] text-neutral-500 mt-1">Add balance to an existing reloadable Virtual Card.</p></div><button onClick={onClose} className="p-2 rounded-xl bg-neutral-900 text-neutral-400"><X/></button></div>
    {result?<div className="p-5 sm:p-7 space-y-5"><div className="rounded-2xl border border-emerald-500/30 bg-emerald-950/30 p-5 text-center"><ShieldCheck className="w-8 h-8 mx-auto text-emerald-400"/><div className="mt-2 text-lg font-black text-white">Reload Submitted</div><div className="text-xs text-neutral-400 mt-1">We will verify your payment before adding the balance.</div><button onClick={copy} className="mt-4 mx-auto flex items-center gap-2 rounded-xl bg-black/50 border border-white/10 px-4 py-2 font-mono text-sm text-[#F3E5AB]">{result.reload_id}{copied?<Check className="w-4 h-4 text-emerald-400"/>:<Copy className="w-4 h-4"/>}</button></div><button onClick={onClose} className="w-full rounded-xl bg-[#D4AF37] text-black font-black py-3">Done</button></div>:<form onSubmit={submit} className="p-4 sm:p-6 space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs text-neutral-300">Order ID / Email / Full Card Number<input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="VCN-2026-0001 or email" className="mt-1 w-full rounded-xl bg-neutral-950 border border-white/10 px-3 py-3 text-sm text-white"/></label><label className="text-xs text-neutral-300">Verification Key (CVV or cardholder name)<input value={securityKey} onChange={e=>setSecurityKey(e.target.value)} className="mt-1 w-full rounded-xl bg-neutral-950 border border-white/10 px-3 py-3 text-sm text-white"/></label></div>
      <div><div className="flex justify-between text-xs text-neutral-300"><span>Reload amount</span><b className="text-[#F3E5AB]">${amount}</b></div><input type="range" min="10" max="20000" step="5" value={amount} onChange={e=>setAmount(Number(e.target.value))} className="w-full mt-3 accent-[#D4AF37]"/><div className="flex justify-between text-[10px] text-neutral-600"><span>$10</span><span>$20,000</span></div></div>
      <div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setMethod('esewa')} className={`rounded-xl border p-3 text-left ${method==='esewa'?'border-emerald-500 bg-emerald-950/30':'border-white/10 bg-neutral-950'}`}><b className="text-sm text-white">eSewa</b><p className="text-[10px] text-neutral-500">Upload receipt</p></button><button type="button" onClick={()=>setMethod('crypto')} className={`rounded-xl border p-3 text-left ${method==='crypto'?'border-indigo-500 bg-indigo-950/30':'border-white/10 bg-neutral-950'}`}><b className="text-sm text-white">Crypto</b><p className="text-[10px] text-neutral-500">TXID verification</p></button></div>
      {method==='esewa'?<div className="rounded-xl border border-white/10 bg-black/30 p-3 space-y-2"><div className="text-xs text-neutral-300">Pay <b className="text-white">Rs. {(amount*Number(settings.exchange_rate||173)).toLocaleString()}</b> via eSewa.</div>{(esewaMethod?.qr_url||settings.esewa_qr_url)&&<img src={esewaMethod?.qr_url||settings.esewa_qr_url} className="w-36 h-36 mx-auto object-contain rounded-lg bg-white"/>}<label className="flex items-center justify-center gap-2 rounded-xl border border-dashed border-white/15 p-3 text-xs text-neutral-400 cursor-pointer"><Upload className="w-4 h-4"/> {shot?'Receipt selected':'Upload payment screenshot'}<input type="file" accept="image/*" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(f)setShot(await fileToData(f))}}/></label></div>:<div className="rounded-xl border border-indigo-500/20 bg-indigo-950/20 p-3 space-y-2"><div className="text-xs text-neutral-300">Send crypto to <span className="font-mono text-indigo-300 break-all">{cryptoMethod?.wallet_address||settings.crypto_payment_address||'Admin has not configured a wallet yet'}</span></div><div className="text-[10px] text-neutral-500">Network: {cryptoMethod?.network||settings.crypto_payment_network||'Ask support'}</div><input required value={txid} onChange={e=>setTxid(e.target.value)} placeholder="Transaction ID / TXID *" className="w-full rounded-xl bg-neutral-950 border border-white/10 px-3 py-3 text-sm text-white"/><input value={txurl} onChange={e=>setTxurl(e.target.value)} placeholder="Blockchain explorer URL (optional)" className="w-full rounded-xl bg-neutral-950 border border-white/10 px-3 py-3 text-sm text-white"/></div>}
      {error&&<div className="rounded-xl border border-red-500/30 bg-red-950/20 p-3 text-xs text-red-300">{error}</div>}<button disabled={loading} className="w-full rounded-xl py-3.5 bg-gradient-to-r from-[#F5D77F] to-[#D4AF37] text-black font-black disabled:opacity-50">{loading?'Submitting…':`Submit $${amount} Reload`}</button><p className="text-[10px] text-center text-neutral-600">Reloads are added only after payment verification.</p>
    </form>}
  </div></div>;
};
